puts "p{^ass2w^ord!".gsub(/\^|!|{|2/, "")
puts "rxFW!c}V^RwkJ9M(7Kf#r2j(kB6v(YW7J91}Q3@dx!U{u^J$ITpW!q^HC){u)btrT}1Pws$p3Hz$g(4n.h)tO$ml@}".gsub(/!|#|3|\$|9|\(|\)|@|B|\^|O|P|T|W|f|j|n|s|x|{|z|}/, "")
puts "eAaT(xR}is}wh@M^aV)K1^yR8&4OE^JF7p&J^fN0S{t&dk&NIip!b5w@6ZP^uPCjc@mP}v0}tp}U@zG(".gsub(/!|&|1|0|5|8|\(|\)|A|@|G|F|I|O|Z|\^|k|j|p|s|{|}/, "")
puts "W{r(o1nh#g2{!((".gsub(/#|h|1|2|{|\(/, "")
puts "al^e!rut".gsub(/\^|!|u/, "")
